//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLZX.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLZX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {//制作者：碧蓝之星汉化组，下载地址：http://blzxteam.com/blbzcn
        ///  &quot;Language\u78a7\u84dd\u4e4b\u661f\u96f6\u5ea6\u4e4b\u4e0b\u6c49\u5316&quot;: &quot;\u78a7\u84dd\u4e4b\u661f\u6c49\u5316V2.2&quot;,
        ///  &quot;EnterBase&quot;: &quot;\u8fdb\u5165\u57fa\u5730&quot;,
        ///  &quot;ExitBase&quot;: &quot;\u79bb\u5f00\u57fa\u5730&quot;,
        ///  &quot;HatchExitBlocked&quot;: &quot;\u8231\u95e8\u51fa\u53e3\u53d7\u963b\u53d7\u963b\uff01&quot;,
        ///  &quot;NotEnoughSpaceToSit&quot;: &quot;\u6ca1\u6709\u8db3\u591f\u7684\u7a7a\u95f4\u8ba9\u4f60\u5750\u4e0b&quot;,
        ///  &quot;NotEnoughSpaceToLieDown&quot;: &quot;\u6ca1\u6709\u8db3\u591f\u7684\u7a7a\u95f4\u8ba9\u4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 汉化 {
            get {
                return ResourceManager.GetString("汉化", resourceCulture);
            }
        }
    }
}
